# Generated by Django 5.2.6 on 2025-09-13 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleanliness', models.CharField(blank=True, choices=[('clean', 'Clean'), ('dirty', 'Dirty'), ('very_dirty', 'Very Dirty')], max_length=20, null=True)),
                ('cleanliness_score', models.IntegerField(blank=True, null=True)),
                ('damage', models.CharField(blank=True, choices=[('none', 'No Damage'), ('scratched', 'Scratched'), ('dented', 'Dented')], max_length=20, null=True)),
                ('damage_score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('appealed', 'Appealed')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='cleanControl.car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='cleanControl.client')),
            ],
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='cleanControl.carcheck')),
            ],
        ),
        migrations.CreateModel(
            name='CarCheckPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_checks/')),
                ('analyzed_result', models.JSONField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('car_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cleanControl.carcheck')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cleanControl.client'),
        ),
    ]
